name: Deploy

on:
  push:
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "21.6.1"

      - run: npm install
      - run: npm run build

      - name: Tar build
        run: cd dist && tar cvfz ../build.tar.gz *

      - name: Make release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build.tar.gz"
